version: 1.0.{build}
configuration: Release
image: Visual Studio 2017
environment:
  SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  access_token:
    secure: 2zi2g91y5yk8KWNadflyPsTTg4+rILTOP6x4wE2FVy6RCAYY5Ku1VTdZZn1I4tHz
install:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: >-
    git submodule update --init --recursive

    choco install sandcastle -y

    choco install monogame -y

    nuget restore
before_build:
- ps: nuget restore PeaceEngine.sln
- ps: nuget restore OpenWheels/src/OpenWheels.sln
- ps: nuget restore 
build:
  project: PeaceEngine.sln
  verbosity: minimal
after_build:
- ps: 
artifacts:
- path: PeaceEngine/bin/Release
- path: Documentation/Help
  name: Documentation
deploy_script:
 - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - ps: git config --global user.email "theplexgate@gmail.com"
 - ps: git config --global user.name "The Fuzzy Riolu"
 - ps: git subtree push --prefix Documentation/Help origin gh-pages
