version: 1.0.{build}
configuration: Release
image: Visual Studio 2017
environment:
  SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  access_token:
    secure: 2zi2g91y5yk8KWNadflyPsTTg4+rILTOP6x4wE2FVy6RCAYY5Ku1VTdZZn1I4tHz
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: >-
    git submodule update --init --recursive

    choco install sandcastle -y

    choco install monogame -y

    nuget restore
before_build:
- ps: nuget restore PeaceEngine.sln
- ps: nuget restore OpenWheels/src/OpenWheels.sln
- ps: nuget restore 
build:
  project: PeaceEngine.sln
  verbosity: minimal
after_build:
- ps: 
artifacts:
- path: PeaceEngine/bin/Release
- path: Documentation/Help
  name: Documentation
deploy:
- provider: Webhook
  url: https://hooks.watercolorgames.net/peace-engine-docs
  authorization:
    secure: x57kTVLkXMOE8EVTzAnk3rCgF5Q01YGUvxNTAWLLKaKvjT1mFYUG0rypGFgyC0WrHIIDC+aPtPcW8fakys9Fgy3dB9hWxcEcTujIVNjNrRc=
